### ISSUE TITLE
Add a warning

### ISSUE THREAD

**Issue by jacklinke** [shinunandakumar/django_execute_code#1]
You should seriously consider adding a warning.

New users might install this without understanding the dangers this project presents.

It's a neat project to develop, but allowing end users to execute arbitrary code like this on the server is pretty much the antithesis of web security.

**Comment by shinunandakumar** [comment]
Hi Jacklinke,
Thanks for the suggestion,
The code execution works only in debug mode and it only allows operations that can be performed in a python shell.
I will add the warning message in the form.
